editor: source

execute:
  cache: false # "Danger Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/_post-render.R"

title: >
  Clara's Pipeline for Processing and Geocoding CNPJs from the Annual Social
  Information Report (RAIS) of the Brazilian Ministry of Labor and
  Employment (MTE)
author: "Gabriel Caldeira, Clara Penz & Daniel Vartanian"
keyword: >
  Pipelines, Data Munging, Data Science, Spatial Data, Geocoding, CNPJ, rstats,
  Brazilian Federal Revenue Service, Open Data, Open Science, Brazil
date: today
date-format: long

website:
  favicon: images/favicon.svg
  site-url: https://cem-usp.github.io/clara-rais-cnpj-geocoding/
  repo-url: https://github.com/cem-usp/clara-rais-cnpj-geocoding/
  issue-url: https://github.com/cem-usp/clara-rais-cnpj-geocoding/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: Center for Metropolitan Studies
  repo-branch: main
  repo-actions: [edit, source, issue]
  search: false
  navbar:
    title: false
    background: "#002554"
    right:
      - icon: github
        href: https://github.com/cem-usp/clara-rais-cnpj-geocoding/
        aria-label: GitHub

lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    locale: en
    language: en-us
    code-fold: false
    code-link: true
    code-tools: false
    df-print: paged
    fig-align: center
    cap-location: top
    lightbox: true
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    theme: [cosmo, scss/styles.scss, brand]
    other-links:
      - text: Center for Metropolitan Studies
        href: https://centrodametropole.fflch.usp.br

google-scholar: false
